# Generated by Django 5.2.6 on 2025-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Slide Title')),
                ('image', models.ImageField(upload_to='hero_slides/', verbose_name='Background Image')),
                ('cta_text', models.CharField(default='See Project', max_length=50, verbose_name='CTA Button Text')),
                ('cta_link', models.URLField(default='/', verbose_name='CTA Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Slide Order')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
    ]
