# Generated by Django 5.2.6 on 2025-09-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carausel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/%y/%m/%d')),
                ('title', models.CharField(max_length=150)),
                ('cta', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='HeroSlide',
        ),
    ]
