# Generated by Django 5.2.6 on 2025-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carausel_delete_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='carausel',
            name='cta_link',
            field=models.URLField(default='/', verbose_name='CTA Link'),
        ),
    ]
