# Generated by Django 5.2.6 on 2025-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carausel_cta_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='cta',
            field=models.CharField(max_length=100, verbose_name='Texte du bouton'),
        ),
        migrations.AlterField(
            model_name='carausel',
            name='cta_link',
            field=models.URLField(default='/', verbose_name='Lien du bouton'),
        ),
        migrations.AlterField(
            model_name='carausel',
            name='image',
            field=models.ImageField(upload_to='pics/%y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='carausel',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titre'),
        ),
    ]
