# Generated by Django 5.2.6 on 2025-09-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_carausel_cta_alter_carausel_cta_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiffreCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=50, verbose_name='Valeur')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Chiffre clé',
                'verbose_name_plural': 'Chiffres clés',
            },
        ),
    ]
