# Generated by Django 5.2.4 on 2025-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chiffrecle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(default='Client', max_length=100, verbose_name='Rôle')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Image')),
            ],
        ),
        migrations.DeleteModel(
            name='ChiffreCle',
        ),
    ]
