# Generated by Django 5.2.4 on 2025-09-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testimonial_delete_chiffrecle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
