# Generated by Django 5.2.4 on 2025-09-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_testimonial_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
