# Generated by Django 5.2.4 on 2025-09-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='title',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icone',
            field=models.ImageField(default='icones_reseaux/default.png', help_text="Télécharger l'icône du réseau social", upload_to='icones_reseaux/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sociallink',
            name='titre',
            field=models.CharField(default=2, help_text="Texte qui s'affiche au survol et texte alternatif", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(help_text='Lien vers le réseau social'),
        ),
    ]
