# Generated by Django 5.2.4 on 2025-09-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_sociallink_icon_remove_sociallink_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='titre',
            field=models.CharField(help_text="Texte qui s'affiche au survol et texte alternatif", max_length=20),
        ),
    ]
