# Generated by Django 5.2.4 on 2025-09-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_sociallink_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('role', models.CharField(default='Client', max_length=50, verbose_name='Rôle du client')),
                ('avis', models.TextField(verbose_name='Avis du client')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du client (admin seulement)')),
                ('est_valide', models.BooleanField(default=False, verbose_name="Approuvé par l'admin")),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
        ),
    ]
