# Generated by Django 5.2.4 on 2025-09-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_temoignage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temoignage',
            name='est_valide',
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du client (facultatif)'),
        ),
    ]
