# Generated by Django 5.2.4 on 2025-09-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_temoignage_est_valide_alter_temoignage_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temoignage',
        ),
    ]
