# Generated by Django 5.2.6 on 2025-09-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la réalisation')),
                ('image', models.ImageField(upload_to='realisations/', verbose_name='Image de la réalisation')),
                ('texte_alt', models.CharField(blank=True, max_length=255, verbose_name='Texte ALT (SEO)')),
                ('categorie', models.CharField(choices=[('photo', 'Photographie'), ('design', 'Design'), ('identite', 'Identité'), ('corporate', 'Corporate'), ('uxui', 'UI/UX')], max_length=50, verbose_name='Catégorie')),
                ('est_large', models.BooleanField(default=False, verbose_name='Large (grid-wide)')),
                ('est_long', models.BooleanField(default=False, verbose_name='Long (grid-long)')),
            ],
        ),
    ]
