# Generated by Django 5.2.6 on 2025-09-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du service')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL optimisée')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Image principale')),
                ('meta_titre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description SEO')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['titre'],
            },
        ),
    ]
