# Generated by Django 5.2.6 on 2025-09-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Catégorie'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
